# Generated by Django 3.2.11 on 2022-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='User name')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='User name')),
            ],
        ),
    ]
