# Generated by Django 3.2.11 on 2022-01-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220109_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lated_update_date',
            new_name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
