# Generated by Django 4.0.1 on 2022-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='regular', editable=False, max_length=10, verbose_name='role'),
        ),
    ]
