# Generated by Django 4.0.1 on 2022-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='email')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('plate', models.CharField(default='', max_length=100, unique=True, verbose_name='licence plate number')),
            ],
            options={
                'verbose_name': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='', max_length=100, unique=True, verbose_name='licence plate number')),
                ('vehicle_type', models.CharField(default='', max_length=100, verbose_name='vehicle type')),
                ('num_passengers', models.IntegerField(default=0, verbose_name='vehicle capacity')),
            ],
            options={
                'verbose_name': 'Vehicle',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='email'),
        ),
    ]
