# Generated by Django 4.0.1 on 2022-01-16 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_driver_vehicle_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ride id')),
                ('ro', models.EmailField(default='', max_length=100, unique=True, verbose_name='ride owner email')),
                ('driver', models.EmailField(default='', max_length=100, unique=True, verbose_name='driver email')),
                ('dest_addr', models.CharField(default='', max_length=100, verbose_name='destination address')),
                ('arrival_time', models.DateTimeField(verbose_name='arrival time')),
                ('headcount', models.IntegerField(default=0, verbose_name='left capacity')),
                ('sharable', models.BooleanField(default='no', verbose_name='share or not')),
                ('status', models.CharField(default='open', max_length=20, verbose_name='status')),
                ('vehicle_type', models.CharField(default='', max_length=100, verbose_name='vehicle type')),
                ('special_request', models.TextField(default='', verbose_name='special request')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Ride',
            },
        ),
        migrations.CreateModel(
            name='Ride_Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ride id')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='all passengers email,')),
                ('party_num_passengers', models.IntegerField(default=0, verbose_name='party number of passengers')),
            ],
            options={
                'verbose_name': 'Ride_Passenger',
            },
        ),
    ]
