# Generated by Django 4.0.1 on 2022-01-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ride_ride_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='licence plate number'),
        ),
    ]
