# Generated by Django 4.0.1 on 2022-01-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_vehicle_id_alter_vehicle_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ride_passenger',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ride id'),
        ),
        migrations.AlterField(
            model_name='ride_passenger',
            name='ride_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ride id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
