# Generated by Django 4.0.1 on 2022-01-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_driver_options_remove_user_role_user_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=100, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=100, verbose_name='lastname'),
        ),
    ]
