# Generated by Django 4.0.1 on 2022-01-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_driver_name_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='Driver_Car',
        ),
    ]
