# Generated by Django 4.0.1 on 2022-01-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_driver_car_id_vehicle_id_alter_driver_car_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(max_length=100, verbose_name='vehicle type'),
        ),
    ]
