# Generated by Django 4.0.1 on 2022-01-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_ride_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='special_request',
        ),
    ]
