# Generated by Django 4.0.1 on 2022-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_ride_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.EmailField(default='', max_length=100, verbose_name='driver email'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ro',
            field=models.EmailField(default='', max_length=100, verbose_name='ride owner email'),
        ),
        migrations.AlterField(
            model_name='ride_passenger',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='all passengers email,'),
        ),
    ]
