# Generated by Django 4.0.1 on 2022-01-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_ride_driver_alter_ride_ro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ride order id'),
        ),
    ]
