# Generated by Django 4.0.1 on 2022-01-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_ride_ride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='num_passengers',
            field=models.IntegerField(default=0, verbose_name='passengers number of this ride'),
        ),
    ]
