# Generated by Django 4.0.1 on 2022-01-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_ride_num_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_passenger',
            name='role',
            field=models.CharField(default='', max_length=50, verbose_name='owner or sharer or driver'),
        ),
    ]
