# Generated by Django 4.0.1 on 2022-01-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_ride_passenger_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='ro',
            new_name='owner_email',
        ),
    ]
