# Generated by Django 4.0.1 on 2022-01-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_ro_ride_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='owner_num_passengers',
            field=models.IntegerField(default=0, verbose_name='owner party passengers number of this ride'),
        ),
    ]
