# Generated by Django 4.0.1 on 2022-01-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_ride_owner_num_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='headcount',
            field=models.IntegerField(default='', verbose_name='left capacity'),
        ),
    ]
