# Generated by Django 4.0.1 on 2022-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_ride_headcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='headcount',
            field=models.CharField(default='', max_length=100, verbose_name='left capacity'),
        ),
    ]
