# Generated by Django 4.0.1 on 2022-01-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_ride_headcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_passenger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride_passenger',
            name='ride_id',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='ride id'),
        ),
    ]
