# Generated by Django 4.0.1 on 2022-01-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_ride_passenger_id_alter_ride_passenger_ride_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_passenger',
            name='ride_id',
            field=models.CharField(editable=False, max_length=50, verbose_name='ride id'),
        ),
    ]
