# Generated by Django 3.2.11 on 2022-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_ride_passenger_ride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='special_request',
            field=models.TextField(blank=True, default='', verbose_name='special request of this ride'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='special_vehicle_info',
            field=models.TextField(blank=True, default='', verbose_name='special vehicle info'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner_num_passengers',
            field=models.IntegerField(default=0, verbose_name='Your party passengers number of this ride'),
        ),
    ]
