# Generated by Django 3.2.11 on 2022-01-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20220127_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_plate',
            field=models.CharField(default='', max_length=100, verbose_name='vehicle plate'),
        ),
    ]
