# Generated by Django 4.0.1 on 2022-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_ride_ride_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_plate',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='vehicle plate'),
        ),
    ]
